//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTestApp.SyncService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opleiding", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncTestApp.SyncService.OpleidingRef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncTestApp.SyncService.OpleidingVal))]
    public partial class Opleiding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpleidingRef", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class OpleidingRef : SyncTestApp.SyncService.Opleiding {
        
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpleidingVal", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class OpleidingVal : SyncTestApp.SyncService.Opleiding {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        private string EduTypeField;
        
        private string EduWorkSpaceField;
        
        private string IdField;
        
        private string NaamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EduType {
            get {
                return this.EduTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EduTypeField, value) != true)) {
                    this.EduTypeField = value;
                    this.RaisePropertyChanged("EduType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EduWorkSpace {
            get {
                return this.EduWorkSpaceField;
            }
            set {
                if ((object.ReferenceEquals(this.EduWorkSpaceField, value) != true)) {
                    this.EduWorkSpaceField = value;
                    this.RaisePropertyChanged("EduWorkSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActieRapport", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class ActieRapport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyncTestApp.SyncService.ActieResultaat ActieResultaatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyncTestApp.SyncService.Trace BerichtenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncTestApp.SyncService.ActieResultaat ActieResultaat {
            get {
                return this.ActieResultaatField;
            }
            set {
                if ((this.ActieResultaatField.Equals(value) != true)) {
                    this.ActieResultaatField = value;
                    this.RaisePropertyChanged("ActieResultaat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncTestApp.SyncService.Trace Berichten {
            get {
                return this.BerichtenField;
            }
            set {
                if ((object.ReferenceEquals(this.BerichtenField, value) != true)) {
                    this.BerichtenField = value;
                    this.RaisePropertyChanged("Berichten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActieResultaat", Namespace="http://teamwise.ogn.eu/services/")]
    public enum ActieResultaat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waarschuwing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Trace", Namespace="http://teamwise.ogn.eu/services/", ItemName="Bericht")]
    [System.SerializableAttribute()]
    public class Trace : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncTestApp.SyncService.ModuleRef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncTestApp.SyncService.ModuleVal))]
    public partial class Module : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleRef", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class ModuleRef : SyncTestApp.SyncService.Module {
        
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleVal", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class ModuleVal : SyncTestApp.SyncService.Module {
        
        private string CodeField;
        
        private string EduCodeField;
        
        private string IdField;
        
        private string LinkedModuleField;
        
        private string NaamField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EduCode {
            get {
                return this.EduCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EduCodeField, value) != true)) {
                    this.EduCodeField = value;
                    this.RaisePropertyChanged("EduCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LinkedModule {
            get {
                return this.LinkedModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedModuleField, value) != true)) {
                    this.LinkedModuleField = value;
                    this.RaisePropertyChanged("LinkedModule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SyncTestApp.SyncService.ModuleRef ModuleField;
        
        private SyncTestApp.SyncService.OpleidingRef OpleidingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SyncTestApp.SyncService.ModuleRef Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleField, value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SyncTestApp.SyncService.OpleidingRef Opleiding {
            get {
                return this.OpleidingField;
            }
            set {
                if ((object.ReferenceEquals(this.OpleidingField, value) != true)) {
                    this.OpleidingField = value;
                    this.RaisePropertyChanged("Opleiding");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wijziging Link", Namespace="http://teamwise.ogn.eu/services/")]
    [System.SerializableAttribute()]
    public partial class WijzigingLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyncTestApp.SyncService.Link NaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyncTestApp.SyncService.Link VanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncTestApp.SyncService.Link Naar {
            get {
                return this.NaarField;
            }
            set {
                if ((object.ReferenceEquals(this.NaarField, value) != true)) {
                    this.NaarField = value;
                    this.RaisePropertyChanged("Naar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncTestApp.SyncService.Link Van {
            get {
                return this.VanField;
            }
            set {
                if ((object.ReferenceEquals(this.VanField, value) != true)) {
                    this.VanField = value;
                    this.RaisePropertyChanged("Van");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://teamwise.ogn.eu/services/", ConfigurationName="SyncService.SyncOpleidingscatalogusService")]
    public interface SyncOpleidingscatalogusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakOpleiding", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakOpleidingRespo" +
            "nse")]
        SyncTestApp.SyncService.ActieRapport MaakOpleiding(SyncTestApp.SyncService.OpleidingVal Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakOpleiding", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakOpleidingRespo" +
            "nse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakOpleidingAsync(SyncTestApp.SyncService.OpleidingVal Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamOpleidin" +
            "g", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamOpleidin" +
            "gResponse")]
        SyncTestApp.SyncService.ActieRapport WijzigNaamOpleiding(SyncTestApp.SyncService.OpleidingVal WijzigingNaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamOpleidin" +
            "g", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamOpleidin" +
            "gResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigNaamOpleidingAsync(SyncTestApp.SyncService.OpleidingVal WijzigingNaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerOpleidin" +
            "g", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerOpleidin" +
            "gResponse")]
        SyncTestApp.SyncService.ActieRapport DeactiveerOpleiding(SyncTestApp.SyncService.OpleidingRef Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerOpleidin" +
            "g", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerOpleidin" +
            "gResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DeactiveerOpleidingAsync(SyncTestApp.SyncService.OpleidingRef Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakModuleResponse" +
            "")]
        SyncTestApp.SyncService.ActieRapport MaakModule(SyncTestApp.SyncService.ModuleVal Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakModuleResponse" +
            "")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakModuleAsync(SyncTestApp.SyncService.ModuleVal Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamModuleRe" +
            "sponse")]
        SyncTestApp.SyncService.ActieRapport WijzigNaamModule(SyncTestApp.SyncService.ModuleVal WijzigingNaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigNaamModuleRe" +
            "sponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigNaamModuleAsync(SyncTestApp.SyncService.ModuleVal WijzigingNaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerModuleRe" +
            "sponse")]
        SyncTestApp.SyncService.ActieRapport DeactiveerModule(SyncTestApp.SyncService.ModuleRef Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerModule", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DeactiveerModuleRe" +
            "sponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DeactiveerModuleAsync(SyncTestApp.SyncService.ModuleRef Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakLinkResponse")]
        SyncTestApp.SyncService.ActieRapport MaakLink(SyncTestApp.SyncService.Link Link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/MaakLinkResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakLinkAsync(SyncTestApp.SyncService.Link Link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigLinkResponse" +
            "")]
        SyncTestApp.SyncService.ActieRapport WijzigLink(SyncTestApp.SyncService.WijzigingLink Wijziging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/WijzigLinkResponse" +
            "")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigLinkAsync(SyncTestApp.SyncService.WijzigingLink Wijziging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/VerwijderLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/VerwijderLinkRespo" +
            "nse")]
        SyncTestApp.SyncService.ActieRapport VerwijderLink(SyncTestApp.SyncService.Link Link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/VerwijderLink", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/VerwijderLinkRespo" +
            "nse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> VerwijderLinkAsync(SyncTestApp.SyncService.Link Link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/Test", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestResponse")]
        SyncTestApp.SyncService.ActieRapport Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/Test", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestFout", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestFoutResponse")]
        SyncTestApp.SyncService.ActieRapport TestFout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestFout", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/TestFoutResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> TestFoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "Opleiding", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "OpleidingResponse")]
        SyncTestApp.SyncService.ActieRapport DoeOnbepaaldeActieOpleiding(SyncTestApp.SyncService.OpleidingVal Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "Opleiding", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "OpleidingResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DoeOnbepaaldeActieOpleidingAsync(SyncTestApp.SyncService.OpleidingVal Opleiding);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "Module", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "ModuleResponse")]
        SyncTestApp.SyncService.ActieRapport DoeOnbepaaldeActieModule(SyncTestApp.SyncService.ModuleVal Module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "Module", ReplyAction="http://teamwise.ogn.eu/services/SyncOpleidingscatalogusService/DoeOnbepaaldeActie" +
            "ModuleResponse")]
        System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DoeOnbepaaldeActieModuleAsync(SyncTestApp.SyncService.ModuleVal Module);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SyncOpleidingscatalogusServiceChannel : SyncTestApp.SyncService.SyncOpleidingscatalogusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncOpleidingscatalogusServiceClient : System.ServiceModel.ClientBase<SyncTestApp.SyncService.SyncOpleidingscatalogusService>, SyncTestApp.SyncService.SyncOpleidingscatalogusService {
        
        public SyncOpleidingscatalogusServiceClient() {
        }
        
        public SyncOpleidingscatalogusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncOpleidingscatalogusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncOpleidingscatalogusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncOpleidingscatalogusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SyncTestApp.SyncService.ActieRapport MaakOpleiding(SyncTestApp.SyncService.OpleidingVal Opleiding) {
            return base.Channel.MaakOpleiding(Opleiding);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakOpleidingAsync(SyncTestApp.SyncService.OpleidingVal Opleiding) {
            return base.Channel.MaakOpleidingAsync(Opleiding);
        }
        
        public SyncTestApp.SyncService.ActieRapport WijzigNaamOpleiding(SyncTestApp.SyncService.OpleidingVal WijzigingNaar) {
            return base.Channel.WijzigNaamOpleiding(WijzigingNaar);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigNaamOpleidingAsync(SyncTestApp.SyncService.OpleidingVal WijzigingNaar) {
            return base.Channel.WijzigNaamOpleidingAsync(WijzigingNaar);
        }
        
        public SyncTestApp.SyncService.ActieRapport DeactiveerOpleiding(SyncTestApp.SyncService.OpleidingRef Opleiding) {
            return base.Channel.DeactiveerOpleiding(Opleiding);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DeactiveerOpleidingAsync(SyncTestApp.SyncService.OpleidingRef Opleiding) {
            return base.Channel.DeactiveerOpleidingAsync(Opleiding);
        }
        
        public SyncTestApp.SyncService.ActieRapport MaakModule(SyncTestApp.SyncService.ModuleVal Module) {
            return base.Channel.MaakModule(Module);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakModuleAsync(SyncTestApp.SyncService.ModuleVal Module) {
            return base.Channel.MaakModuleAsync(Module);
        }
        
        public SyncTestApp.SyncService.ActieRapport WijzigNaamModule(SyncTestApp.SyncService.ModuleVal WijzigingNaar) {
            return base.Channel.WijzigNaamModule(WijzigingNaar);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigNaamModuleAsync(SyncTestApp.SyncService.ModuleVal WijzigingNaar) {
            return base.Channel.WijzigNaamModuleAsync(WijzigingNaar);
        }
        
        public SyncTestApp.SyncService.ActieRapport DeactiveerModule(SyncTestApp.SyncService.ModuleRef Module) {
            return base.Channel.DeactiveerModule(Module);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DeactiveerModuleAsync(SyncTestApp.SyncService.ModuleRef Module) {
            return base.Channel.DeactiveerModuleAsync(Module);
        }
        
        public SyncTestApp.SyncService.ActieRapport MaakLink(SyncTestApp.SyncService.Link Link) {
            return base.Channel.MaakLink(Link);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> MaakLinkAsync(SyncTestApp.SyncService.Link Link) {
            return base.Channel.MaakLinkAsync(Link);
        }
        
        public SyncTestApp.SyncService.ActieRapport WijzigLink(SyncTestApp.SyncService.WijzigingLink Wijziging) {
            return base.Channel.WijzigLink(Wijziging);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> WijzigLinkAsync(SyncTestApp.SyncService.WijzigingLink Wijziging) {
            return base.Channel.WijzigLinkAsync(Wijziging);
        }
        
        public SyncTestApp.SyncService.ActieRapport VerwijderLink(SyncTestApp.SyncService.Link Link) {
            return base.Channel.VerwijderLink(Link);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> VerwijderLinkAsync(SyncTestApp.SyncService.Link Link) {
            return base.Channel.VerwijderLinkAsync(Link);
        }
        
        public SyncTestApp.SyncService.ActieRapport Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public SyncTestApp.SyncService.ActieRapport TestFout() {
            return base.Channel.TestFout();
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> TestFoutAsync() {
            return base.Channel.TestFoutAsync();
        }
        
        public SyncTestApp.SyncService.ActieRapport DoeOnbepaaldeActieOpleiding(SyncTestApp.SyncService.OpleidingVal Opleiding) {
            return base.Channel.DoeOnbepaaldeActieOpleiding(Opleiding);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DoeOnbepaaldeActieOpleidingAsync(SyncTestApp.SyncService.OpleidingVal Opleiding) {
            return base.Channel.DoeOnbepaaldeActieOpleidingAsync(Opleiding);
        }
        
        public SyncTestApp.SyncService.ActieRapport DoeOnbepaaldeActieModule(SyncTestApp.SyncService.ModuleVal Module) {
            return base.Channel.DoeOnbepaaldeActieModule(Module);
        }
        
        public System.Threading.Tasks.Task<SyncTestApp.SyncService.ActieRapport> DoeOnbepaaldeActieModuleAsync(SyncTestApp.SyncService.ModuleVal Module) {
            return base.Channel.DoeOnbepaaldeActieModuleAsync(Module);
        }
    }
}
